### ISSUE TITLE
Use maven for facebook android

### ISSUE THREAD

**Issue by jcassani** [TomGrill/gdx-facebook#1]
Hi, first of all, thanks for this great contribution, I suggest you to use

    compile 'com.facebook.android:facebook-android-sdk:4.0.0'

Instead of having the jar in the android/libs folder

**Comment by TomGrill** [comment]
Hi, i cannot quite remember but for some reason Eclipse wasn't able to use the maven method. So i had to add it this way. I will look into this when after the weekend.

**Comment by TomGrill** [comment]
Ok, I looked further into it and this is the problem:

When i use maven for facebook-sdk eclipse is longer able to find the required classes. I assume it has something to do with facebook-sdk coming in aar format. Since google did not help me out so far I will keep it as it is until a solution pops up somehow.

![fbaar](https://cloud.githubusercontent.com/assets/9935213/7583816/10d3c24a-f899-11e4-8ab9-fe50e156cd85.png)
